<?php

namespace AppBundle\Repository;
	
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}